# Web端口
server:
  port: 9876

spring:
  # DB配置
  datasource:
    url: jdbc:mysql://xxx.com:ooo/project?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: xxxxxx
    password: oooooo
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 30000
  # RabbitMQ配置
  rabbitmq:
    addresses: xxxxxx.00:oooooo
    username: xxxxxx
    password: oooooo
    virtual-host: /
    connection-timeout: 10_000
    # 消费者配置
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5
        acknowledge-mode: manual
        prefetch: 5
# 日志
logging:
  config: classpath:logback.xml