# 端口，配置为非常用的，避免冲突
server:
  port: 9876

spring:
  # RabbitMQ配置
  rabbitmq:
    addresses: 139.155.14.94:5672
    username: shr
    password: swun6237
    virtual-host: shr
    connection-timeout: 10_000
    # 消费者配置
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
        acknowledge-mode: manual
        prefetch: 1