# 端口
server:
  servlet:
    context-path: /portal
  port: 8888

spring:
  data:
    # elasticsearch
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: xxxxxx.xx:oooo

binlog:
  host: xxxxxxxx.com
  port: 3306
  schema: project
  username: xxxxxx
  password: oooooo