# 端口
server:
  servlet:
    context-path: /portal
  port: 8888

spring:
  data:
    # elasticsearch
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: thunderclap.cn:9300
      repositories:
        enabled: true

binlog:
  host: thunderclap.cn
  port: 3306
  schema: project
  username: zhh
  password: 123456