CREATE TABLE `shr_position` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `unique_key` varchar(32) NOT NULL DEFAULT '' COMMENT '网站职位唯一标识',
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
  `source` tinyint(1) NOT NULL DEFAULT '0' COMMENT '来源：1-智联，2-拉勾，3-boss直聘，0-未知',
  `salary` varchar(16) NOT NULL DEFAULT '' COMMENT '薪水',
  `city` varchar(32) NOT NULL DEFAULT '' COMMENT '城市',
  `work_exp` varchar(16) NOT NULL DEFAULT '' COMMENT '工作经验',
  `education` varchar(16) NOT NULL DEFAULT '' COMMENT '学历',
  `welfare` varchar(128) NOT NULL DEFAULT '' COMMENT '福利',
  `description` varchar(5000) NOT NULL DEFAULT '' COMMENT '描述',
  `label` varchar(128) NOT NULL DEFAULT '' COMMENT '标签',
  `work_address` varchar(256) NOT NULL DEFAULT '' COMMENT '工作地址',
  `publish_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  `url` varchar(256) NOT NULL DEFAULT '' COMMENT '详情链接',
  `company_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '公司id',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_user` varchar(64) DEFAULT '' COMMENT '最后更新人',
  `last_update_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除：1-是，0否',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_unique_key` (`unique_key`,`source`,`is_deleted`) USING BTREE,
  KEY `idx_name` (`name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=126 DEFAULT CHARSET=utf8mb4 COMMENT='职位表';